### ISSUE TITLE
Doesn't Play well with others

### ISSUE THREAD

**Issue by dgoring** [jonaskulhanek/gulp-resolve-url#1]
It seems to rewrite the sourcemap with absolute paths, rather than just updating the relative paths.
And i believe this is interfering with gulp-clean-css 

```js
gulp.task('sass', function () {
  var styles = gulp.src('app/assets/stylesheets/app.scss')
    .pipe(sourcemaps.init())
    .pipe(sass({
      includePaths: 'node_modules',
    }))
    .pipe(resolve({
      attempts: 1,
      root: 'public/css'
    }))
    // .pipe(useref({
    //   base: 'public/css',
    //   pathTransform: function(newAssetFile, cssFilePathRel, urlMatch, options) {
    //     var path = urlMatch
    //       .replace(/^(\.\.[\/\\])+(\.\.[\/\\])/g, '$2')
    //       .replace(/^(\.\.[\/\\])node_modules/g, '$1vendor');

    //     return path;
    //   }
    // }))
    .pipe(cleanCSS({
      level: util.env.production ? 1 : 0,
      rebaseTo: 'public',
      sourceMap: false,
    }))
    .on('error', handleError);

  if(!util.env.production)
  {
    styles = styles.pipe(sourcemaps.write());
  }

  return styles.pipe(gulp.dest('public/css'));
});
```
On run i get this
```
C:\path\node_modules\vinyl-sourcemaps-apply\node_modules\source-map\lib\source-map-generator.js:177
        throw new Error(
        ^

Error: SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map's "file" property. Both were omitted.
    at SourceMapGenerator_applySourceMap [as applySourceMap] (C:\path\node_modules\vinyl-sourcemaps-apply\node_modules\source-map\lib\source-map-generator.js:177:15)
    at applySourceMap (C:\path\node_modules\vinyl-sourcemaps-apply\index.js:27:15)
    at C:\path\node_modules\gulp-clean-css\index.js:65:9
    at C:\path\node_modules\clean-css\lib\clean.js:109:9
    at C:\path\node_modules\clean-css\lib\reader\read-sources.js:26:64
    at loadOriginalSources (C:\path\node_modules\clean-css\lib\reader\load-original-sources.js:26:5)
    at Object.callback (C:\path\node_modules\clean-css\lib\reader\read-sources.js:26:14)
    at doApplySourceMaps (C:\path\node_modules\clean-css\lib\reader\apply-source-maps.js:61:23)
    at applySourceMaps (C:\path\node_modules\clean-css\lib\reader\apply-source-maps.js:33:5)
    at Object.callback (C:\path\node_modules\clean-css\lib\reader\read-sources.js:25:12)
```
But if i comment out resolve it seems to work fine

**Comment by jkulhanek** [comment]
Try to explicitly provide the base path as noted in readme when calling the gulp.src. Did it help? Can you also provide a test case to the test/ folder?

**Comment by OskarPersson** [comment]
I'm having the same problem with gulp-clean-css@2.4.0 and gulp-autoprefixer@5.0.0. When I have at least one of those in the same gulp task before gulp-resolve-url I get the same error as @dgoring.

Putting gulp-resolve-url after gulp-clean-css and/or gulp-autoprefixer doesn't generate any errors but the work done by gulp-clean-css and/or gulp-autoprefixer is not saved

**Comment by Nobody-x** [comment]
Still an issue for me, any task after gulp-resolve-url that use the sourcemap fail. Looks like other packages issues, see https://github.com/terinjokes/gulp-uglify/issues/53 and https://github.com/sindresorhus/gulp-autoprefixer/issues/2
